import os, json, datetime

out = [f"# AutoGenerated at {datetime.datetime.now()}", "from classes import *", "", "SPRITES = {"]
for file in os.listdir("./resources/data/"):
    with open("./resources/data/" + file) as f:
        data = json.load(f)
        out.append(f"\t'{file.replace('.json', '').upper()}': {data['TYPE']}({data['TEXTURES']}),")
for img in os.listdir("./resources/imgs/"):
    out.append(f"\t'{img.split('.')[0]}': Sprite('./resources/imgs/{img}'),")
out.append("}")

with open("./resources/datapack.py", "w") as f:
    f.write("\n".join(out))
