# AutoGenerated at 2025-01-31 18:57:30.831207
from classes import *

SPRITES = {
	'FLOOR': Sprite(pg.image.load('./resources/textures/floor.png')),
	'PLAYER': Sprite(pg.image.load('./resources/textures/player.png')),
	'WALL': Sprite(pg.image.load('./resources/textures/wall.png')),
	'WALLCORNER': Sprite(pg.image.load('./resources/textures/wallCorner.png')),
	'WALLINNER': Sprite(pg.image.load('./resources/textures/wallInner.png')),
	'background': Sprite(pg.image.load('./resources/imgs/background.jpg')),
}